version: "3"
services:
  mongo:
    image: mongo:3.6.3
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: devdexter/repay-backend
    container_name: "repay-backend"
    ports:
      - 8080:8080
    links:
      - mongo
